server:
  port: 4000
spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://121.40.181.197:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    alicloud:
      access-key: LTAI5tABipxw153Ucj1R6Hds
      secret-key: BXbJ3TDjMfEW6mNlzECh5LctgMmdoE
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.stonebridge.mallproduct: debug